/* Mood Swings — card database (133 cards, first edition).
 * Facts (name, color, die value, rarity) follow the published game;
 * effect summaries are original concise paraphrases for quick reference.
 * Fields: id, n=name, c=color, v=base value, d=die ('w' white fixed | 'b' black variable),
 * s=secondary value (rotate 180°), r=rarity, t=effect summary.
 */
(function (global) {
  'use strict';
  var CARDS = [
    {id:1,n:"Altruism",c:"white",v:3,d:"w",s:7,r:"rare",t:"If the discard pile isn't empty, becomes 7; then each player (starting with the next in turn order) takes a random card from the discard pile into hand, and the rest of the discard pile is shuffled onto the bottom of the deck."},
    {id:2,n:"Benevolence",c:"white",v:2,d:"w",s:null,r:"uncommon",t:"May play an extra mood this turn if it shares no color with your other moods."},
    {id:3,n:"Charity",c:"white",v:1,d:"w",s:null,r:"common",t:"May play an extra mood this turn."},
    {id:4,n:"Chivalry",c:"white",v:3,d:"b",s:5,r:"common",t:"Worth 5 while in play if you didn't take the first turn this round."},
    {id:5,n:"Complacency",c:"white",v:4,d:"w",s:null,r:"common",t:"No abilities. A plain 4."},
    {id:6,n:"Conviction",c:"white",v:2,d:"w",s:null,r:"uncommon",t:"Choose a mood: its owner tucks it to the bottom of the deck and draws a card."},
    {id:7,n:"Courage",c:"white",v:1,d:"w",s:null,r:"common",t:"Choose up to two players; each discards one of their moods worth 5 or more."},
    {id:8,n:"Dignity",c:"white",v:3,d:"w",s:5,r:"common",t:"You may discard a 0–3 card from hand; if you do, this becomes 5 (rotate to its secondary value)."},
    {id:9,n:"Discipline",c:"white",v:6,d:"b",s:3,r:"common",t:"Drops to 3 while two or more black and/or red moods are in play."},
    {id:10,n:"Disillusionment",c:"white",v:2,d:"w",s:null,r:"rare",t:"Starting with the next player, each player may name a color; discard every other mood of the named colors."},
    {id:11,n:"Encouragement",c:"white",v:3,d:"w",s:null,r:"uncommon",t:"Choose a mood with a secondary value; while in play, it scores the higher of its two values."},
    {id:12,n:"Faith",c:"white",v:3,d:"w",s:null,r:"uncommon",t:"You may discard a green or blue card from hand to suppress any mood (worth 0, turned sideways) as long as Faith stays in play."},
    {id:13,n:"Friendliness",c:"white",v:2,d:"w",s:null,r:"uncommon",t:"May play an extra mood this turn if its top-right value is even (0, 2, 4, or 6)."},
    {id:14,n:"Guilt",c:"white",v:2,d:"w",s:null,r:"uncommon",t:"Choose: suppress one black or red mood, or suppress ALL black and red moods, while Guilt stays in play."},
    {id:15,n:"Honor",c:"white",v:3,d:"w",s:null,r:"rare",t:"Choose a player; they take the first turn every round (doesn't change who draws), while Honor is in play."},
    {id:16,n:"Idealism",c:"white",v:0,d:"w",s:null,r:"mythic",t:"May play an extra mood this turn; all your moods with secondary values score the higher of the two."},
    {id:17,n:"Kindness",c:"white",v:2,d:"w",s:null,r:"uncommon",t:"May play an extra mood this turn if its top-right value is odd (1, 3, or 5)."},
    {id:18,n:"Loyalty",c:"white",v:3,d:"b",s:6,r:"common",t:"Becomes 6 while two or more green and/or blue moods are in play."},
    {id:19,n:"Meekness",c:"white",v:1,d:"w",s:null,r:"rare",t:"Suppresses all moods worth 5 or more while it stays in play."},
    {id:20,n:"Pacifism",c:"white",v:1,d:"w",s:null,r:"common",t:"Choose up to two players; suppress one mood of each while Pacifism stays in play."},
    {id:21,n:"Patience",c:"white",v:5,d:"b",s:1,r:"common",t:"Worth only 1 the round you play it (black die: recheck at scoring)."},
    {id:22,n:"Pride",c:"white",v:1,d:"w",s:null,r:"rare",t:"Choose a player with more moods than you; keep playing extra moods until you match their count."},
    {id:23,n:"Repentance",c:"white",v:2,d:"w",s:null,r:"uncommon",t:"Name a number; suppress all other moods with that value until end of round."},
    {id:24,n:"Scorn",c:"white",v:2,d:"w",s:null,r:"mythic",t:"Suppress any mood until end of round; each time you play another mood, you may suppress a mood sharing its color until end of round."},
    {id:25,n:"Shame",c:"white",v:3,d:"w",s:null,r:"rare",t:"You may discard a card from hand; suppress all other moods sharing the discarded card's color while Shame stays in play."},
    {id:26,n:"Validation",c:"white",v:1,d:"w",s:null,r:"mythic",t:"May play an extra mood this turn; each time you play a 0- or 1-valued mood, you may play another extra mood."},
    {id:27,n:"Ambivalence",c:"blue",v:6,d:"b",s:3,r:"common",t:"Drops to 3 while two or more red and/or green moods are in play."},
    {id:28,n:"Anxiety",c:"blue",v:2,d:"w",s:null,r:"common",t:"Choose up to two players; each returns one of their odd-valued moods to hand."},
    {id:29,n:"Avoidance",c:"blue",v:3,d:"w",s:null,r:"rare",t:"Choose left or right; each player gives one of their moods to the next player in that direction."},
    {id:30,n:"Bashfulness",c:"blue",v:6,d:"w",s:null,r:"common",t:"After scoring, if you won the round, tuck this to the bottom of the deck and draw a card."},
    {id:31,n:"Confusion",c:"blue",v:4,d:"w",s:null,r:"uncommon",t:"Choose left or right; each player gives a card from hand to the next player in that direction."},
    {id:32,n:"Creativity",c:"blue",v:0,d:"b",s:null,r:"rare",t:"Play as a copy of any mood (dice, color, and abilities) while it stays in play."},
    {id:33,n:"Curiosity",c:"blue",v:3,d:"w",s:6,r:"common",t:"Choose a player; they reveal a random card from hand — if it shares a color with any mood, this becomes 6 (rotate)."},
    {id:34,n:"Denial",c:"blue",v:1,d:"w",s:null,r:"rare",t:"Choose two other moods; if they share a color or value, return both to their owners' hands."},
    {id:35,n:"Disorientation",c:"blue",v:0,d:"w",s:null,r:"rare",t:"Name a number; return all other moods with that value to their owners' hands."},
    {id:36,n:"Doubt",c:"blue",v:2,d:"w",s:null,r:"uncommon",t:"Reveal any number of cards from hand, tuck them to the bottom of the deck and redraw that many; next round, no one may play moods of the revealed colors."},
    {id:37,n:"Duplicity",c:"blue",v:0,d:"w",s:null,r:"mythic",t:"May play an extra mood this turn; each further mood you play triggers its after-playing effect twice."},
    {id:38,n:"Fear",c:"blue",v:0,d:"w",s:null,r:"common",t:"Return another of your moods to your hand, then play an extra mood this turn."},
    {id:39,n:"Fickleness",c:"blue",v:0,d:"w",s:null,r:"uncommon",t:"Return every other mood of the most common color(s) to its owner's hand."},
    {id:40,n:"Guile",c:"blue",v:0,d:"w",s:null,r:"mythic",t:"Cost: discard 2 cards. Steal an opponent's mood — it becomes yours."},
    {id:41,n:"Hesitation",c:"blue",v:2,d:"w",s:null,r:"uncommon",t:"Choose: return a red or green mood to its owner's hand, or return ALL red and green moods."},
    {id:42,n:"Imagination",c:"blue",v:3,d:"w",s:null,r:"uncommon",t:"Choose a color; every mood counts as that color and no other, while in play."},
    {id:43,n:"Indecisiveness",c:"blue",v:3,d:"w",s:null,r:"uncommon",t:"Choose any number of opponents with 2+ moods; each returns a random mood to hand."},
    {id:44,n:"Indifference",c:"blue",v:4,d:"w",s:null,r:"common",t:"No abilities. A plain 4."},
    {id:45,n:"Insecurity",c:"blue",v:2,d:"w",s:null,r:"uncommon",t:"May play an extra mood this turn; after scoring, that extra mood returns to your hand."},
    {id:46,n:"Neurosis",c:"blue",v:5,d:"w",s:null,r:"common",t:"Cost: return one or more of your moods to your hand."},
    {id:47,n:"Obsession",c:"blue",v:3,d:"b",s:6,r:"common",t:"Becomes 6 while two or more white and/or black moods are in play."},
    {id:48,n:"Panic",c:"blue",v:1,d:"w",s:null,r:"common",t:"Choose up to two players; each returns one of their moods (not this one) to hand."},
    {id:49,n:"Rationalization",c:"blue",v:3,d:"w",s:null,r:"rare",t:"Choose: tuck your hand to the bottom of the deck and redraw, or everyone passes their hand left/right."},
    {id:50,n:"Regret",c:"blue",v:4,d:"w",s:null,r:"rare",t:"Cost: return two of your moods to hand. Then return an opponent's mood to their hand."},
    {id:51,n:"Sneakiness",c:"blue",v:5,d:"w",s:null,r:"mythic",t:"Choose an opponent; after scoring this round, swap scores with them before the winner is decided."},
    {id:52,n:"Worry",c:"blue",v:3,d:"w",s:null,r:"uncommon",t:"You may return one of your white/black moods to hand; if you do, return up to two other moods worth 3 or less to their owners' hands."},
    {id:53,n:"Ambition",c:"black",v:2,d:"w",s:null,r:"common",t:"You may discard a card from hand to play an extra mood this turn."},
    {id:54,n:"Angst",c:"black",v:3,d:"w",s:null,r:"uncommon",t:"You may discard one of your blue/red moods; if you do, play an extra mood this turn from the discard pile."},
    {id:55,n:"Apathy",c:"black",v:4,d:"w",s:null,r:"common",t:"No abilities. A plain 4."},
    {id:56,n:"Betrayal",c:"black",v:6,d:"w",s:null,r:"uncommon",t:"Give one of your moods to another player; after scoring it returns to you."},
    {id:57,n:"Bitterness",c:"black",v:0,d:"w",s:null,r:"uncommon",t:"Discard every other mood of the most common color(s)."},
    {id:58,n:"Condescension",c:"black",v:3,d:"w",s:null,r:"common",t:"You may give a card from hand to another player; if you do, this becomes 6 (rotate)."},
    {id:59,n:"Contempt",c:"black",v:1,d:"w",s:null,r:"uncommon",t:"Choose: discard a green or white mood, or discard ALL green and white moods."},
    {id:60,n:"Corruption",c:"black",v:2,d:"w",s:null,r:"rare",t:"Choose: tuck up to two cards from the discard pile to the bottom of the deck and draw that many, or this round's winner scores two round wins instead of one."},
    {id:61,n:"Cruelty",c:"black",v:3,d:"w",s:null,r:"uncommon",t:"Choose any number of opponents with 2+ moods; each discards a random mood."},
    {id:62,n:"Cynicism",c:"black",v:3,d:"w",s:6,r:"uncommon",t:"You may put a card from the discard pile into an opponent's hand; if you do, this becomes 6 (rotate)."},
    {id:63,n:"Disgust",c:"black",v:6,d:"b",s:3,r:"common",t:"Drops to 3 while two or more green and/or white moods are in play."},
    {id:64,n:"Envy",c:"black",v:0,d:"b",s:null,r:"rare",t:"Cost: discard one of your moods. Gains +2 for each mood your moodiest opponent has (recheck at scoring)."},
    {id:65,n:"Grief",c:"black",v:0,d:"w",s:null,r:"rare",t:"You may play up to two extra moods this turn from the discard pile."},
    {id:66,n:"Hate",c:"black",v:0,d:"w",s:null,r:"common",t:"You may tuck any mood to the bottom of the deck; if you do, draw a card."},
    {id:67,n:"Intimidation",c:"black",v:1,d:"w",s:null,r:"rare",t:"Choose another player; they reveal a card from hand into your hand, and you may play it as an extra mood this turn."},
    {id:68,n:"Malice",c:"black",v:0,d:"w",s:null,r:"mythic",t:"Choose a player with 2+ moods; they pick two of them, then discard those plus every other mood sharing either color."},
    {id:69,n:"Melancholy",c:"black",v:3,d:"w",s:null,r:"rare",t:"While in play, you may play moods from the discard pile as if from your hand."},
    {id:70,n:"Misery",c:"black",v:2,d:"b",s:8,r:"uncommon",t:"Becomes 8 (6+2) while the discard pile holds two or more cards of the same color."},
    {id:71,n:"Paranoia",c:"black",v:2,d:"w",s:null,r:"uncommon",t:"Choose a player holding cards; they reveal a random card from hand to the bottom of the deck, and you draw a card."},
    {id:72,n:"Pity",c:"black",v:3,d:"b",s:6,r:"common",t:"Becomes 6 while two or more blue and/or red moods are in play."},
    {id:73,n:"Rejection",c:"black",v:0,d:"w",s:null,r:"rare",t:"Choose two other moods; if they share a color or value, discard both."},
    {id:74,n:"Sadness",c:"black",v:0,d:"b",s:null,r:"mythic",t:"Gains +2 for each card in the discard pile (recheck at scoring)."},
    {id:75,n:"Self-Loathing",c:"black",v:6,d:"w",s:null,r:"common",t:"Cost: discard one or more of your moods. A flat 6 once paid."},
    {id:76,n:"Spite",c:"black",v:1,d:"w",s:null,r:"common",t:"Choose up to two players; each discards one of their even-valued moods (0 counts as even)."},
    {id:77,n:"Superiority",c:"black",v:3,d:"b",s:7,r:"common",t:"Becomes 7 (6+1) while you have more moods than every other player."},
    {id:78,n:"Suspicion",c:"black",v:3,d:"w",s:null,r:"common",t:"Choose any number of players; each discards a card from hand."},
    {id:79,n:"Vanity",c:"black",v:0,d:"b",s:null,r:"mythic",t:"Gains +1 per mood you have (including itself); +3 each instead if your hand is empty."},
    {id:80,n:"Anger",c:"red",v:0,d:"w",s:null,r:"uncommon",t:"You may discard any number of moods totaling 5 or less."},
    {id:81,n:"Animosity",c:"red",v:3,d:"w",s:5,r:"uncommon",t:"Becomes 5 while any opponent holds 3+ cards in hand."},
    {id:82,n:"Arrogance",c:"red",v:2,d:"b",s:null,r:"uncommon",t:"Steal an opponent's white or blue mood (they choose which); return it when Arrogance leaves play."},
    {id:83,n:"Boredom",c:"red",v:4,d:"w",s:null,r:"common",t:"No abilities. A plain 4."},
    {id:84,n:"Bravado",c:"red",v:3,d:"w",s:null,r:"common",t:"You may discard another of your moods to play an extra mood this turn."},
    {id:85,n:"Chaos",c:"red",v:6,d:"w",s:null,r:"mythic",t:"Shuffle all moods together and redeal them one at a time in turn order, starting with you."},
    {id:86,n:"Compulsion",c:"red",v:3,d:"w",s:null,r:"common",t:"Choose another player; they give you a card from their hand (their choice)."},
    {id:87,n:"Embarrassment",c:"red",v:3,d:"w",s:5,r:"common",t:"You may discard a 4–6 card from hand; if you do, this becomes 5 (rotate)."},
    {id:88,n:"Excitement",c:"red",v:3,d:"b",s:6,r:"common",t:"Becomes 6 while two or more black and/or green moods are in play."},
    {id:89,n:"Exhilaration",c:"red",v:0,d:"w",s:null,r:"mythic",t:"Cost: discard one of your moods. While in play, your moods are scored an extra time (double your total)."},
    {id:90,n:"Frustration",c:"red",v:6,d:"b",s:3,r:"common",t:"Drops to 3 while two or more white and/or blue moods are in play."},
    {id:91,n:"Fury",c:"red",v:4,d:"w",s:null,r:"uncommon",t:"Every player discards one of their highest-valued moods."},
    {id:92,n:"Glee",c:"red",v:0,d:"b",s:6,r:"common",t:"Worth 6 the round you play it (black die: recheck at scoring)."},
    {id:93,n:"Gluttony",c:"red",v:2,d:"w",s:null,r:"uncommon",t:"May play an extra mood this turn; after scoring, that extra mood is discarded."},
    {id:94,n:"Hostility",c:"red",v:3,d:"w",s:null,r:"uncommon",t:"You may discard one of your black/green moods; if you do, discard up to two moods worth 3 or less."},
    {id:95,n:"Infatuation",c:"red",v:3,d:"w",s:9,r:"rare",t:"You may discard two of your other moods; if you do, this becomes 9 (6+3, rotate)."},
    {id:96,n:"Instability",c:"red",v:2,d:"w",s:null,r:"rare",t:"Choose two of one opponent's moods; they give you one of their choice, and you give them one of yours."},
    {id:97,n:"Passion",c:"red",v:0,d:"w",s:null,r:"rare",t:"While scoring, you may also score one opponent's mood as your own (they still score it too)."},
    {id:98,n:"Rage",c:"red",v:2,d:"w",s:null,r:"uncommon",t:"You may discard every other mood worth 3 or less."},
    {id:99,n:"Rebellion",c:"red",v:2,d:"w",s:null,r:"uncommon",t:"Choose 0, 1, 2, or 3; discard every other mood with that value."},
    {id:100,n:"Recklessness",c:"red",v:0,d:"w",s:null,r:"rare",t:"You may borrow an opponent's mood until after scoring; then, after scoring, tuck this to the bottom of the deck and draw a card."},
    {id:101,n:"Shock",c:"red",v:2,d:"w",s:null,r:"common",t:"Choose up to two players; each discards one of their moods worth 3 or less."},
    {id:102,n:"Stubbornness",c:"red",v:3,d:"w",s:null,r:"rare",t:"At the start of each of your turns, if anyone has more moods than you, you may play an extra mood that turn."},
    {id:103,n:"Thrill",c:"red",v:1,d:"w",s:null,r:"mythic",t:"You may return any number of your other moods to hand, then play that many extra moods this turn."},
    {id:104,n:"Triumph",c:"red",v:3,d:"b",s:5,r:"common",t:"Becomes 5 if you went first this round."},
    {id:105,n:"Wrath",c:"red",v:0,d:"w",s:null,r:"rare",t:"You may discard every other mood."},
    {id:106,n:"Zeal",c:"red",v:3,d:"w",s:null,r:"common",t:"You may tuck a card from hand to the bottom of the deck; if you do, draw a card."},
    {id:107,n:"Awe",c:"green",v:4,d:"w",s:null,r:"rare",t:"Cancels scoring this round entirely: no winner, no draws, no Hurt Feelings. You choose who goes first next round."},
    {id:108,n:"Bliss",c:"green",v:2,d:"w",s:null,r:"mythic",t:"Cost: discard a card. Your moods sharing the discarded card's color are scored two extra times (triple)."},
    {id:109,n:"Celebration",c:"green",v:3,d:"b",s:7,r:"common",t:"Becomes 7 (6+1) while your moods span more colors than each other player's."},
    {id:110,n:"Cheer",c:"green",v:3,d:"w",s:5,r:"common",t:"You may discard an even-valued card from hand; if you do, this becomes 5 (rotate)."},
    {id:111,n:"Delight",c:"green",v:3,d:"w",s:5,r:"common",t:"You may discard an odd-valued card from hand; if you do, this becomes 5 (rotate)."},
    {id:112,n:"Determination",c:"green",v:3,d:"b",s:6,r:"common",t:"Becomes 6 while three or more moods share a color (anywhere in play)."},
    {id:113,n:"Disregard",c:"green",v:6,d:"b",s:3,r:"common",t:"Drops to 3 while two or more blue and/or black moods are in play."},
    {id:114,n:"Eagerness",c:"green",v:2,d:"w",s:null,r:"uncommon",t:"May play an extra mood this turn if it shares a color with one of your moods."},
    {id:115,n:"Enjoyment",c:"green",v:3,d:"b",s:6,r:"common",t:"Becomes 6 while two or more red and/or white moods are in play."},
    {id:116,n:"Enthusiasm",c:"green",v:0,d:"w",s:null,r:"uncommon",t:"While scoring, you may score one of your moods an extra time (double it)."},
    {id:117,n:"Euphoria",c:"green",v:0,d:"b",s:null,r:"rare",t:"Gains +1 for every mood in play (yours and everyone's)."},
    {id:118,n:"Fascination",c:"green",v:3,d:"w",s:7,r:"uncommon",t:"You may reveal a blue/black card from hand and give it to another player; if you do, this becomes 7 (6+1, rotate)."},
    {id:119,n:"Fondness",c:"green",v:0,d:"b",s:7,r:"uncommon",t:"Becomes 7 (6+1) while every player has 3+ moods."},
    {id:120,n:"Generosity",c:"green",v:6,d:"w",s:null,r:"common",t:"Choose an opponent; they may play an extra mood on their next turn."},
    {id:121,n:"Grace",c:"green",v:0,d:"w",s:null,r:"rare",t:"Each of your turns, you may play an extra mood from the discard pile if it shares a color with one of your moods."},
    {id:122,n:"Happiness",c:"green",v:2,d:"b",s:8,r:"uncommon",t:"Becomes 8 (6+2) while any player has both a red and a white mood."},
    {id:123,n:"Harmony",c:"green",v:2,d:"w",s:null,r:"uncommon",t:"You may play an extra mood this turn from the discard pile."},
    {id:124,n:"Hope",c:"green",v:0,d:"w",s:null,r:"rare",t:"You may play an extra mood on each of your turns."},
    {id:125,n:"Joy",c:"green",v:3,d:"w",s:null,r:"common",t:"You may play an extra mood on your next turn."},
    {id:126,n:"Laziness",c:"green",v:4,d:"w",s:null,r:"common",t:"No abilities. A plain 4."},
    {id:127,n:"Love",c:"green",v:4,d:"b",s:12,r:"mythic",t:"Becomes 12 (6+6) while all five colors are represented among moods (including itself)."},
    {id:128,n:"Nostalgia",c:"green",v:0,d:"w",s:null,r:"common",t:"You may take a card from the discard pile into hand, then play an extra mood this turn."},
    {id:129,n:"Serenity",c:"green",v:3,d:"b",s:6,r:"uncommon",t:"Becomes 6 while you have an even number of moods."},
    {id:130,n:"Sloth",c:"green",v:3,d:"b",s:null,r:"rare",t:"Gains +1 for each card in your hand."},
    {id:131,n:"Tranquility",c:"green",v:3,d:"b",s:6,r:"uncommon",t:"Becomes 6 while you have an odd number of moods."},
    {id:132,n:"Vulnerability",c:"green",v:1,d:"b",s:7,r:"rare",t:"Becomes 7 (6+1) if a card was put into the discard pile this round."},
    {id:133,n:"Wonder",c:"green",v:0,d:"b",s:null,r:"mythic",t:"Choose a color; gains +2 for each mood and each discard-pile card of that color."},
    {id:134,n:"Love",c:"green",v:4,d:"b",s:12,r:"headliner",t:"Headliner (special distribution, but playable). Becomes 12 while white, blue, black, red, and green moods are all in play (including itself)."},
    {id:135,n:"Hurt Feelings",c:"colorless",v:0,d:"w",s:null,r:"helper",sp:1,t:"Helper card — not played as a mood. In 3–4 player games, the round's lowest scorer gets Hurt Feelings: one extra mood next turn. Lowest-score ties go to whoever took the latest turn."}
  ];

  // Normalize compact fields to the public shape the engine/UI expect.
  var FULL = CARDS.map(function (c) {
    return {
      id: c.id, name: c.n, color: c.c, value: c.v,
      die: c.d === 'b' ? 'black' : 'white',
      secondary: c.s, rarity: c.r, summary: c.t,
      special: !!c.sp
    };
  });

  var BY_ID = {};
  FULL.forEach(function (c) { BY_ID[c.id] = c; });

  function byId(id) { return BY_ID[id] || null; }
  function search(q) {
    q = (q || '').trim().toLowerCase();
    if (!q) return FULL;
    return FULL.filter(function (c) { return c.name.toLowerCase().indexOf(q) !== -1; });
  }

  global.MSCards = { all: FULL, byId: byId, search: search };
})(typeof window !== 'undefined' ? window : globalThis);
